---
swagger: "2.0"

info:
  version: v1
  title: test服务
  description: test服务

basePath: /api/v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json

tags:
  - name: test
    description: 测试方法


paths:
  /test/getName:
    $ref: v1/test/get-id.yml

definitions:
  ResultDTO:
    type: object
    description: 结果基本信息
    properties:
      status:
        type: integer
        format: int32
        description: 状态码
        example: 200
      datas:
        type: object
        description: 结果信息
        example: xxx
      message:
        type: string
        description: 结果状态描述

  PageResultDTO:
    type: object
    description: 分页信息
    properties:
      status:
        type: integer
        format: int32
        description: 状态码
        example: 200
      message:
        type: string
        description: 结果状态描述
      page:
        type: integer
        format: int32
        description: 当前页码
        example: 1
      pageSize:
        type: integer
        format: int32
        description: 每页显示件数
        example: 1
      totalDataNum:
        type: integer
        format: int32
        description: 总件数
        example: 10
      totalPageNum:
        type: integer
        format: int32
        description: 总页数
        example: 10
      datas:
        type: object
        description: 结果信息
        example: xxx
