server:
  port: 8080

spring:
  redis:
    database: 0
    host: docker
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
    timeout: 1000
